
-- 데이터베이스 생성 및 변경
CREATE DATABASE LIONGYM;
USE LIONGYM;

-- 테이블 삭제
DROP TABLE IF EXISTS MEMBERS;
DROP TABLE IF EXISTS TRAINERS;

-- 테이블 생성
CREATE TABLE TRAINERS (
    ID INT PRIMARY KEY AUTO_INCREMENT ,
    NAME VARCHAR(100) NOT NULL ,
    PHONE VARCHAR(13) NOT NULL ,
    BASE_SALARY INT NOT NULL ,
    BONUS INT ,
    LESSONS INT ,
    REG_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MEMBERS (
    ID INT PRIMARY KEY AUTO_INCREMENT ,
    NAME VARCHAR(100) NOT NULL ,
    PHONE VARCHAR(13) NOT NULL,
    TRAINER_ID VARCHAR(100),
    SESSION INT ,
    REG_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 테이블 확인
DESC TRAINERS;
DESC MEMBERS;

-- 기본 데이터 INSERT
INSERT INTO TRAINERS (NAME, PHONE, BASE_SALARY, BONUS, LESSONS)
VALUES ('김이두', '010-1111-1111', 2000000, 30000, 10);
INSERT INTO TRAINERS (NAME, PHONE, BASE_SALARY, BONUS, LESSONS)
VALUES ('이덤벨', '010-2222-2222', 1500000, 50000, 20);
INSERT INTO TRAINERS (NAME, PHONE, BASE_SALARY, BONUS, LESSONS)
VALUES ('박코어', '010-3333-3333', 1000000, 40000, 0);

INSERT INTO MEMBERS (NAME, PHONE)
VALUES ('김회원', '010-5555-5555');
INSERT INTO MEMBERS (NAME, PHONE, TRAINER_ID, SESSION)
VALUES ('이회원', '010-6666-6666', 1, 5);
INSERT INTO MEMBERS (NAME, PHONE, TRAINER_ID, SESSION)
VALUES ('박회원', '010-7777-7777', 2, 15);
INSERT INTO MEMBERS (NAME, PHONE, TRAINER_ID, SESSION)
VALUES ('정회원', '010-8888-8888', 3, 2);
INSERT INTO MEMBERS (NAME, PHONE, TRAINER_ID, SESSION)
VALUES ('최회원', '010-9999-9999', 1, 23);

-- 목록 조회
SELECT * FROM TRAINERS;
SELECT * FROM MEMBERS;

-- 트레이너의 정보와 총 급여를 계산하여 조회
SELECT ID,
       NAME,
       BASE_SALARY,
       BONUS,
       LESSONS,
       (BASE_SALARY + BONUS * LESSONS) AS TOTAL_SALARY
FROM TRAINERS
ORDER BY ID;

-- 회원과 담당 트레이너를 조회
SELECT M.ID      AS M_ID,
       M.NAME    AS M_NAME,
       M.PHONE   AS M_PHONE,
       CASE WHEN T.ID IS NOT NULL THEN 'Y' ELSE 'N' END AS PT_YN,
       COALESCE(T.ID, '-')    AS T_ID,
       COALESCE(T.NAME, '-')  AS T_NAME,
       COALESCE(T.PHONE, '-') AS T_PHONE,
       COALESCE(M.SESSION, 0) AS SESSION_CNT
FROM MEMBERS M
LEFT JOIN TRAINERS T
ON M.TRAINER_ID = T.ID
ORDER BY M.ID;





